services:
  php:
    image: php:8.4.6-fpm
    container_name: php
    volumes:
      - ../www:/var/www/html
    networks:
      custom_net:
        ipv4_address: 172.25.0.10

networks:
  custom_net:
    