services:
   backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-backend
    networks:
      - custom_net
    env_file:
      - ./backend/.env

networks:
  custom_net:
    