server {
    listen 80;
    server_name localhost;

   # Proxy all frontend requests to React dev server
    location / {
    proxy_pass http://react-app:5173;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

    # Proxy API requests to Node backend
    location /api {
    proxy_pass http://node-backend:3001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
