services:
  react:
    build:
     context: ./react
     dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
      - php    
    networks:
      custom_net:
        ipv4_address: 172.25.0.14

networks:
  custom_net:
    