services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-backend
    networks:
      - custom_net
    env_file:
      - ./backend/.env

  db:
    image: mysql:9.2.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - custom_net

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - ./react:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - custom_net

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - react
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - custom_net

volumes:
  db_data:

networks:
  custom_net:
    driver: bridge
