services:
  db:
    image: mysql:9.2.0
    container_name: db
    ports:
      - "20455:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      custom_net:
        ipv4_address: 172.25.0.12

volumes:
  db_data:

networks:
  custom_net:
    external: true